version: '3.4'

services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_SEED: -1251937210
      ONLINE_MODE: false
    labels:
      - "traefik.enable=false"
    ports:
      - 19132:19132/udp
    volumes:
      - ${USERHOME}/server/minecraft:/data
    stdin_open: true
    tty: true

