---
version: "3.1"
services:
#
# HOMEASSISTANT SERVER
#
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ=${TIMEZONE}
      - HC_IGNORE_SSL=True
    volumes:
      - ${USERHOME}/server/home-assistant/:/config
      # - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      # Enable home-assistant handler entrypoint on http.
      - "traefik.http.routers.home-assistant-http.entrypoints=web"
      # Define home-assistant handler http host.
      - "traefik.http.routers.home-assistant-http.rule=Host(`home.${DOCKER_BASE_URL}`)"
      # Define http middleware and redirection to https.
      - "traefik.http.routers.home-assistant-http.middlewares=home-assistant-https"
      - "traefik.http.middlewares.home-assistant-https.redirectscheme.scheme=https"
      # Enable home-assistant handler entrypoint on https.
      - "traefik.http.routers.home-assistant.entrypoints=websecure"
      # Define home-assistant handler host.
      - "traefik.http.routers._home-assistant.rule=Host(`home.${DOCKER_BASE_URL}`)"
      # Instructs home-assistant that the current router is dedicated to HTTPS requests only.
      - "traefik.http.routers._home-assistant.tls=true"
      # Define on which network Traefik is operating.
      # - "traefik.docker.network=docker-home-net"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
  # nodered:
  #   container_name: nodered
  #   image: nodered/node-red
  #   restart: unless-stopped
  #   ports:
  #     - "1880:1880/tcp"
  #   environment:
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - ./docker/node_red:/data
  #   depends_on:
  #     - homeassistant
