name: Check running

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy environment file
        run: cp .env.sample .env

      - name: Run setup.sh
        run: ./setup.sh

      - name: create volume foders
        run: mkdir -p /server/nextcloud/config/ /photos

      - name: Create the network
        run: docker network create docker-home-net

      - name: Run docker-compose
        run: cd home-assistant && docker-compose up -d
